# .streamlit/secrets.toml

[connections.sqlserver]
dialect = "mssql"
driver = "pyodbc"
host = "10.120.11.10"
port = 1433
database = "SBO_HELA"
username = "sa"
password = "Hela2017*"
# Si estás usando pyodbc, a menudo necesitas especificar el driver exacto instalado en tu sistema:
query = {driver = ["ODBC Driver 17 for SQL Server"]}
